stages: 
  - build


frontend:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  script:
    - export
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${NEXUS_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${NEXUS_USER}" "${NEXUS_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/src/frontend"
      --dockerfile "${CI_PROJECT_DIR}/src/frontend/Dockerfile"
      --destination "${NEXUS_REGISTRY}/frontend:${CI_COMMIT_TAG}"
  rules:
    - if: $CI_COMMIT_TAG