haproxy_frontends:
  - haproxy_frontend_name: 'k8s-api'
    haproxy_frontend_bind_address: '*'
    haproxy_frontend_port: 6443
    haproxy_frontend_mode: 'tcp'
    haproxy_default_backend_name: 'k8s-api'
  - haproxy_frontend_name: 'weave-socks'
    haproxy_frontend_bind_address: '*'
    haproxy_frontend_port: 80
    haproxy_frontend_mode: 'tcp'
    haproxy_default_backend_name: 'weave-socks'

haproxy_backends:
  - haproxy_backend_name: 'k8s-api'
    haproxy_backend_mode: 'tcp'
    haproxy_backend_balance_method: 'roundrobin'
    haproxy_backend_httpchk: ''
    haproxy_backend_servers: "{{ hostvars['localhost'].KUBE_CONTROL_PLANE_NODES | to_json | replace('__PORT__', '6443') | from_json  }}"
  - haproxy_backend_name: 'weave-socks'
    haproxy_backend_mode: 'tcp'
    haproxy_backend_balance_method: 'roundrobin'
    haproxy_backend_httpchk: ''
    haproxy_backend_servers: "{{ hostvars['localhost'].KUBE_NODES | to_json | replace('__PORT__', '30001') | from_json }}"