---
- name: Create a GitLab Project {{ item.reponame }}
  community.general.gitlab_project:
    api_url: "{{ gitlab_url }}"
    api_username: "{{ gitlab_user }}"
    api_password: "{{ gitlab_password }}"
    name: "{{ item.reponame }}"
    visibility: internal
    group: "{{ gitlab_group.group.id }}"
  register: project
- name: Clone {{ item.reponame }} repository
  ansible.builtin.shell: |
    repopath={{ item.repopath }}
    reponame={{ item.reponame }}
    rm -rf $reponame
    git clone $repopath $reponame
    cd $reponame
    git remote add gitlab-origin http://{{ gitlab_user }}:{{ gitlab_password }}@{{ gitlab_host }}/{{ gitlab_group.group.name }}/${reponame}.git
    git push --all gitlab-origin
    git push --tags gitlab-origin
  when: project.changed