inventory:
  # ansible inventory structure
  all:
    children:
      k8s_cluster:
        children:
          kube_node:
            hosts:
              master01:
              master02:
              master03:  
          kube_control_plane:
            hosts:
              master01:
              master02:
              master03:
          etcd:
            hosts:
              master01:
              master02:
              master03:        
      # balancers are optional
      balancers:
        hosts:
          balancer01:
      gitlab:
        hosts:
          gitlab01:
  
params:
  # list of machine parameters
  # name - hostname
  # cpu - count of cpu cores
  # memory - memory in Mb
  # disk - root disk size in Gb (this parameter doesn't work with virtualbox)
  master01:
    name: master01
    cpu: 2
    memory: 4096
    disk: 20
  master02:
    name: master02
    cpu: 2
    memory: 4096
    disk: 20
  master03:
    name: master03
    cpu: 2
    memory: 4096
    disk: 20
  balancer01:
    name: balancer01
    cpu: 2
    memory: 512
    disk: 5
  balancer02:
    name: balancer02
    cpu: 2
    memory: 512
    disk: 5
  gitlab01:
    name: gitlab01
    cpu: 2
    memory: 4096
    disk: 40