inventory:
  # ansible inventory structure
  # every host mentioned in this section must be specified in the params: section
  all:
    children:
      k8s_cluster:
        children:
          kube_node:
            hosts:
              master11:  
          kube_control_plane:
            hosts:
              master11: 
          etcd:
            hosts:
              master11: 
      gitlab:
        hosts:
          gitlab11:
      nexus:
        hosts:
          nexus11:
  
params:
  # provider specifies the terrafrom-provider which will create node resources
  # available values: "ychosted" and "virtualbox"
  provider: ychosted
  # hosts specification
  # every host must have defined name, cpu, memory, disk, public_ip
  master11:
    name: master11
    cpu: 4
    memory: 4096
    disk: 40
    public_ip: true
  balancer11:
    name: balancer11
    cpu: 2
    memory: 512
    disk: 5
  balancer12:
    name: balancer12
    cpu: 2
    memory: 512
    disk: 5
  gitlab11:
    name: gitlab11
    cpu: 2
    memory: 4096
    disk: 40
    public_ip: true
  nexus11:
    name: nexus11
    cpu: 2
    memory: 4096
    disk: 40
    public_ip: true