# nginx_remove_default_vhost: true
# nginx_upstreams:
# - name: k8s
#   # strategy: "ip_hash" # "least_conn", etc.
#   # keepalive: 16 # optional
#   servers: "{{ groups['kube_node'] | map('extract', hostvars, ['ansible_host']) | product([':6443']) | map('join') }}"

# nginx_vhosts:
# - listen: 6443
#   server_name: _
#   extra_parameters: |
#     listen 443;
#     location / {
#       proxy_pass https://k8s;
#     }

haproxy_frontend_name: 'k8s-api'
haproxy_frontend_bind_address: '*'
haproxy_frontend_port: 6443
haproxy_frontend_mode: 'tcp'

haproxy_backend_name: 'k8s-api'
haproxy_backend_mode: 'tcp'
haproxy_backend_balance_method: 'roundrobin'
haproxy_backend_httpchk: ''

# List of backend servers.
haproxy_backend_servers: "{{ hostvars['localhost'].K8S_NODES  }}"


# frontend k8s-api
#     bind :::6443 v4v6
#     mode tcp
#     default_backend k8s-api
# backend k8s-api
#     balance roundrobin
#     mode tcp
#     option tcp-check
#     default-server inter 10s downinter 5s rise 2 fall 2 slowstart 60s maxconn 250 maxqueue 256 weight 100
#     server k8s-1 192.168.9.130:6443 check
#     server k8s-2 192.168.9.131:6443 check
#     server k8s-3 192.168.9.132:6443 check